project:
  type: book
  output-dir: docs

book:
  title: "Titre du document"
  author: "Auteur du document"
  date: "Date du document"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-overflow: wrap
    theme: lumen
    toc-title: "Sommaire"
    number-sections: true
    highlight-style: github
    cover-image: ressources/bloc-etat
    css: ressources/styles.css
  pdf:
    documentclass: scrreprt
    sansfont: Raleway
    mainfont: Avenir Next LT Pro
    toc-title: "Sommaire"
    include-before-body: ressources/page_de_garde.tex
    include-in-header: ressources/preamble.tex
    include-after-body: ressources/lastPage.tex
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
  docx:
    reference-doc: ressources/template.docx
    toc-title: "Sommaire"




